name: chat
description: A new Flutter application.

publish_to: 'none'
version: 2.4.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #COMMON
  cupertino_icons: ^1.0.6
  nb_utils: ^6.1.2
  intl: ^0.19.0
  html: ^0.15.4
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.0
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  onesignal_flutter: ^5.1.0
  #  image_crop: any
  url_launcher: ^6.2.4
  share: ^2.0.4
  package_info_plus: ^5.0.1
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  qr_code_scanner: ^1.0.1
  device_info_plus: ^9.1.2
  sqflite: ^2.3.2
  flutter_feed_reaction: ^0.0.6


  #FIREBASE
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_storage: ^11.5.6
  firebase_database: ^10.3.8
  paginate_firestore: ^1.0.3+1

  #SIGN_IN
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  country_code_picker: ^3.0.0
  otp_text_field: ^1.1.3

  #VIDEO_cALL
  agora_rtc_engine: ^6.2.6

  #ATTACHMENT
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  just_audio: ^0.9.36
  video_player: ^2.8.2
  record: ^4.4.4
  video_thumbnail: ^0.5.3
  photo_view: ^0.14.0
  open_file: ^3.3.2
  webview_flutter: ^4.5.0
  emoji_picker_flutter: ^1.6.3

  #location
  geolocator: ^11.0.0
  location: ^5.0.3

  #ENCRYPTION
  encrypt: ^5.0.1

  flutter_localizations:
    sdk: flutter

  permission_handler_platform_interface: any
  path: any
  path_provider: any
  http: any
  async: any
  flutter_cache_manager: any
  rxdart: any
  collection: any
dependency_overrides:
  cloud_firestore: ^4.15.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - lang/
    - assets/Icons/


